# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: runtime/v1/data.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'runtime/v1/data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15runtime/v1/data.proto\x12\nruntime.v1\";\n\x13GetTokenDataRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x10\n\x08token_id\x18\x02 \x01(\t\">\n\x14GetTokenDataResponse\x12\x10\n\x08token_id\x18\x01 \x01(\t\x12\x14\n\x0cpayload_json\x18\x02 \x01(\x0c\x32`\n\x0bRuntimeData\x12Q\n\x0cGetTokenData\x12\x1f.runtime.v1.GetTokenDataRequest\x1a .runtime.v1.GetTokenDataResponseB1Z/piper_agent/runtime/pkg/pb/runtime/v1;runtimev1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'runtime.v1.data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z/piper_agent/runtime/pkg/pb/runtime/v1;runtimev1'
  _globals['_GETTOKENDATAREQUEST']._serialized_start=37
  _globals['_GETTOKENDATAREQUEST']._serialized_end=96
  _globals['_GETTOKENDATARESPONSE']._serialized_start=98
  _globals['_GETTOKENDATARESPONSE']._serialized_end=160
  _globals['_RUNTIMEDATA']._serialized_start=162
  _globals['_RUNTIMEDATA']._serialized_end=258
# @@protoc_insertion_point(module_scope)
