# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from runtime.v1 import execute_pb2 as runtime_dot_v1_dot_execute__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in runtime/v1/execute_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RuntimeExecuteStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunTemplate = channel.unary_unary(
                '/runtime.v1.RuntimeExecute/RunTemplate',
                request_serializer=runtime_dot_v1_dot_execute__pb2.RunTemplateRequest.SerializeToString,
                response_deserializer=runtime_dot_v1_dot_execute__pb2.RunTemplateResponse.FromString,
                _registered_method=True)
        self.CancelRun = channel.unary_unary(
                '/runtime.v1.RuntimeExecute/CancelRun',
                request_serializer=runtime_dot_v1_dot_execute__pb2.CancelRunRequest.SerializeToString,
                response_deserializer=runtime_dot_v1_dot_execute__pb2.CancelRunResponse.FromString,
                _registered_method=True)
        self.SubscribeRun = channel.unary_stream(
                '/runtime.v1.RuntimeExecute/SubscribeRun',
                request_serializer=runtime_dot_v1_dot_execute__pb2.SubscribeRunRequest.SerializeToString,
                response_deserializer=runtime_dot_v1_dot_execute__pb2.RunEvent.FromString,
                _registered_method=True)


class RuntimeExecuteServicer:
    """Missing associated documentation comment in .proto file."""

    def RunTemplate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RuntimeExecuteServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RunTemplate': grpc.unary_unary_rpc_method_handler(
                    servicer.RunTemplate,
                    request_deserializer=runtime_dot_v1_dot_execute__pb2.RunTemplateRequest.FromString,
                    response_serializer=runtime_dot_v1_dot_execute__pb2.RunTemplateResponse.SerializeToString,
            ),
            'CancelRun': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelRun,
                    request_deserializer=runtime_dot_v1_dot_execute__pb2.CancelRunRequest.FromString,
                    response_serializer=runtime_dot_v1_dot_execute__pb2.CancelRunResponse.SerializeToString,
            ),
            'SubscribeRun': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeRun,
                    request_deserializer=runtime_dot_v1_dot_execute__pb2.SubscribeRunRequest.FromString,
                    response_serializer=runtime_dot_v1_dot_execute__pb2.RunEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'runtime.v1.RuntimeExecute', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('runtime.v1.RuntimeExecute', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RuntimeExecute:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RunTemplate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/runtime.v1.RuntimeExecute/RunTemplate',
            runtime_dot_v1_dot_execute__pb2.RunTemplateRequest.SerializeToString,
            runtime_dot_v1_dot_execute__pb2.RunTemplateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/runtime.v1.RuntimeExecute/CancelRun',
            runtime_dot_v1_dot_execute__pb2.CancelRunRequest.SerializeToString,
            runtime_dot_v1_dot_execute__pb2.CancelRunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/runtime.v1.RuntimeExecute/SubscribeRun',
            runtime_dot_v1_dot_execute__pb2.SubscribeRunRequest.SerializeToString,
            runtime_dot_v1_dot_execute__pb2.RunEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
