# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from piper_agent.pb.runtime.v1 import meta_pb2 as runtime_dot_v1_dot_meta__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in runtime/v1/meta_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RuntimeMetaStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListTemplates = channel.unary_unary(
                '/runtime.v1.RuntimeMeta/ListTemplates',
                request_serializer=runtime_dot_v1_dot_meta__pb2.ListTemplatesRequest.SerializeToString,
                response_deserializer=runtime_dot_v1_dot_meta__pb2.ListTemplatesResponse.FromString,
                _registered_method=True)
        self.GetTemplate = channel.unary_unary(
                '/runtime.v1.RuntimeMeta/GetTemplate',
                request_serializer=runtime_dot_v1_dot_meta__pb2.GetTemplateRequest.SerializeToString,
                response_deserializer=runtime_dot_v1_dot_meta__pb2.GetTemplateResponse.FromString,
                _registered_method=True)
        self.ListProxies = channel.unary_unary(
                '/runtime.v1.RuntimeMeta/ListProxies',
                request_serializer=runtime_dot_v1_dot_meta__pb2.ListProxiesRequest.SerializeToString,
                response_deserializer=runtime_dot_v1_dot_meta__pb2.ListProxiesResponse.FromString,
                _registered_method=True)


class RuntimeMetaServicer:
    """Missing associated documentation comment in .proto file."""

    def ListTemplates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTemplate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListProxies(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RuntimeMetaServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListTemplates': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTemplates,
                    request_deserializer=runtime_dot_v1_dot_meta__pb2.ListTemplatesRequest.FromString,
                    response_serializer=runtime_dot_v1_dot_meta__pb2.ListTemplatesResponse.SerializeToString,
            ),
            'GetTemplate': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTemplate,
                    request_deserializer=runtime_dot_v1_dot_meta__pb2.GetTemplateRequest.FromString,
                    response_serializer=runtime_dot_v1_dot_meta__pb2.GetTemplateResponse.SerializeToString,
            ),
            'ListProxies': grpc.unary_unary_rpc_method_handler(
                    servicer.ListProxies,
                    request_deserializer=runtime_dot_v1_dot_meta__pb2.ListProxiesRequest.FromString,
                    response_serializer=runtime_dot_v1_dot_meta__pb2.ListProxiesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'runtime.v1.RuntimeMeta', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('runtime.v1.RuntimeMeta', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RuntimeMeta:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListTemplates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/runtime.v1.RuntimeMeta/ListTemplates',
            runtime_dot_v1_dot_meta__pb2.ListTemplatesRequest.SerializeToString,
            runtime_dot_v1_dot_meta__pb2.ListTemplatesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTemplate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/runtime.v1.RuntimeMeta/GetTemplate',
            runtime_dot_v1_dot_meta__pb2.GetTemplateRequest.SerializeToString,
            runtime_dot_v1_dot_meta__pb2.GetTemplateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListProxies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/runtime.v1.RuntimeMeta/ListProxies',
            runtime_dot_v1_dot_meta__pb2.ListProxiesRequest.SerializeToString,
            runtime_dot_v1_dot_meta__pb2.ListProxiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
