# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: runtime/v1/meta.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'runtime/v1/meta.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from piper_agent.pb.common.v1 import types_pb2 as common_dot_v1_dot_types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15runtime/v1/meta.proto\x12\nruntime.v1\x1a\x15\x63ommon/v1/types.proto\"U\n\x14ListTemplatesRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x0c\n\x04page\x18\x02 \x01(\x05\x12\x0c\n\x04size\x18\x03 \x01(\x05\x12\r\n\x05query\x18\x04 \x01(\t\"Q\n\x15ListTemplatesResponse\x12)\n\ttemplates\x18\x01 \x03(\x0b\x32\x16.common.v1.TemplateDoc\x12\r\n\x05total\x18\x02 \x01(\x03\"=\n\x12GetTemplateRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x13\n\x0btemplate_id\x18\x02 \x01(\t\"?\n\x13GetTemplateResponse\x12(\n\x08template\x18\x01 \x01(\x0b\x32\x16.common.v1.TemplateDoc\"D\n\x08ProxyDoc\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06\x64omain\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\t\"T\n\x12ListProxiesRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x0c\n\x04page\x18\x02 \x01(\x05\x12\x0c\n\x04size\x18\x03 \x01(\x05\x12\x0e\n\x06status\x18\x04 \x01(\t\"K\n\x13ListProxiesResponse\x12%\n\x07proxies\x18\x01 \x03(\x0b\x32\x14.runtime.v1.ProxyDoc\x12\r\n\x05total\x18\x02 \x01(\x03\x32\x83\x02\n\x0bRuntimeMeta\x12T\n\rListTemplates\x12 .runtime.v1.ListTemplatesRequest\x1a!.runtime.v1.ListTemplatesResponse\x12N\n\x0bGetTemplate\x12\x1e.runtime.v1.GetTemplateRequest\x1a\x1f.runtime.v1.GetTemplateResponse\x12N\n\x0bListProxies\x12\x1e.runtime.v1.ListProxiesRequest\x1a\x1f.runtime.v1.ListProxiesResponseB1Z/piper_agent/runtime/pkg/pb/runtime/v1;runtimev1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'runtime.v1.meta_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z/piper_agent/runtime/pkg/pb/runtime/v1;runtimev1'
  _globals['_LISTTEMPLATESREQUEST']._serialized_start=60
  _globals['_LISTTEMPLATESREQUEST']._serialized_end=145
  _globals['_LISTTEMPLATESRESPONSE']._serialized_start=147
  _globals['_LISTTEMPLATESRESPONSE']._serialized_end=228
  _globals['_GETTEMPLATEREQUEST']._serialized_start=230
  _globals['_GETTEMPLATEREQUEST']._serialized_end=291
  _globals['_GETTEMPLATERESPONSE']._serialized_start=293
  _globals['_GETTEMPLATERESPONSE']._serialized_end=356
  _globals['_PROXYDOC']._serialized_start=358
  _globals['_PROXYDOC']._serialized_end=426
  _globals['_LISTPROXIESREQUEST']._serialized_start=428
  _globals['_LISTPROXIESREQUEST']._serialized_end=512
  _globals['_LISTPROXIESRESPONSE']._serialized_start=514
  _globals['_LISTPROXIESRESPONSE']._serialized_end=589
  _globals['_RUNTIMEMETA']._serialized_start=592
  _globals['_RUNTIMEMETA']._serialized_end=851
# @@protoc_insertion_point(module_scope)
