# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: runtime/v1/template.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'runtime/v1/template.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common.v1 import types_pb2 as common_dot_v1_dot_types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19runtime/v1/template.proto\x12\nruntime.v1\x1a\x15\x63ommon/v1/types.proto\"\x8b\x01\n\x17ValidateTemplateRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12(\n\x08template\x18\x02 \x01(\x0b\x32\x16.common.v1.TemplateDoc\x12\x13\n\x0btemplate_id\x18\x03 \x01(\t\x12\x1d\n\x04vars\x18\x04 \x01(\x0b\x32\x0f.common.v1.Vars\"R\n\x18ValidateTemplateResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12*\n\x0b\x64iagnostics\x18\x02 \x03(\x0b\x32\x15.common.v1.Diagnostic\"U\n\x15UpsertTemplateRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12(\n\x08template\x18\x02 \x01(\x0b\x32\x16.common.v1.TemplateDoc\"-\n\x16UpsertTemplateResponse\x12\x13\n\x0btemplate_id\x18\x01 \x01(\t2\xc9\x01\n\x0fRuntimeTemplate\x12]\n\x10ValidateTemplate\x12#.runtime.v1.ValidateTemplateRequest\x1a$.runtime.v1.ValidateTemplateResponse\x12W\n\x0eUpsertTemplate\x12!.runtime.v1.UpsertTemplateRequest\x1a\".runtime.v1.UpsertTemplateResponseB1Z/piper_agent/runtime/pkg/pb/runtime/v1;runtimev1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'runtime.v1.template_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z/piper_agent/runtime/pkg/pb/runtime/v1;runtimev1'
  _globals['_VALIDATETEMPLATEREQUEST']._serialized_start=65
  _globals['_VALIDATETEMPLATEREQUEST']._serialized_end=204
  _globals['_VALIDATETEMPLATERESPONSE']._serialized_start=206
  _globals['_VALIDATETEMPLATERESPONSE']._serialized_end=288
  _globals['_UPSERTTEMPLATEREQUEST']._serialized_start=290
  _globals['_UPSERTTEMPLATEREQUEST']._serialized_end=375
  _globals['_UPSERTTEMPLATERESPONSE']._serialized_start=377
  _globals['_UPSERTTEMPLATERESPONSE']._serialized_end=422
  _globals['_RUNTIMETEMPLATE']._serialized_start=425
  _globals['_RUNTIMETEMPLATE']._serialized_end=626
# @@protoc_insertion_point(module_scope)
