# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from runtime.v1 import template_pb2 as runtime_dot_v1_dot_template__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in runtime/v1/template_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RuntimeTemplateStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ValidateTemplate = channel.unary_unary(
                '/runtime.v1.RuntimeTemplate/ValidateTemplate',
                request_serializer=runtime_dot_v1_dot_template__pb2.ValidateTemplateRequest.SerializeToString,
                response_deserializer=runtime_dot_v1_dot_template__pb2.ValidateTemplateResponse.FromString,
                _registered_method=True)
        self.UpsertTemplate = channel.unary_unary(
                '/runtime.v1.RuntimeTemplate/UpsertTemplate',
                request_serializer=runtime_dot_v1_dot_template__pb2.UpsertTemplateRequest.SerializeToString,
                response_deserializer=runtime_dot_v1_dot_template__pb2.UpsertTemplateResponse.FromString,
                _registered_method=True)


class RuntimeTemplateServicer:
    """Missing associated documentation comment in .proto file."""

    def ValidateTemplate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpsertTemplate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RuntimeTemplateServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ValidateTemplate': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateTemplate,
                    request_deserializer=runtime_dot_v1_dot_template__pb2.ValidateTemplateRequest.FromString,
                    response_serializer=runtime_dot_v1_dot_template__pb2.ValidateTemplateResponse.SerializeToString,
            ),
            'UpsertTemplate': grpc.unary_unary_rpc_method_handler(
                    servicer.UpsertTemplate,
                    request_deserializer=runtime_dot_v1_dot_template__pb2.UpsertTemplateRequest.FromString,
                    response_serializer=runtime_dot_v1_dot_template__pb2.UpsertTemplateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'runtime.v1.RuntimeTemplate', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('runtime.v1.RuntimeTemplate', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RuntimeTemplate:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ValidateTemplate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/runtime.v1.RuntimeTemplate/ValidateTemplate',
            runtime_dot_v1_dot_template__pb2.ValidateTemplateRequest.SerializeToString,
            runtime_dot_v1_dot_template__pb2.ValidateTemplateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpsertTemplate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/runtime.v1.RuntimeTemplate/UpsertTemplate',
            runtime_dot_v1_dot_template__pb2.UpsertTemplateRequest.SerializeToString,
            runtime_dot_v1_dot_template__pb2.UpsertTemplateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
