// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: common/v1/errors.proto

package commonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ErrorCode is returned in gRPC status details (Phase A: documented; Phase B+: enforced).
type ErrorCode int32

const (
	ErrorCode_ERROR_CODE_UNSPECIFIED         ErrorCode = 0
	ErrorCode_ERROR_CODE_INVALID_ARGUMENT    ErrorCode = 1
	ErrorCode_ERROR_CODE_NOT_FOUND           ErrorCode = 2
	ErrorCode_ERROR_CODE_FAILED_PRECONDITION ErrorCode = 3
	ErrorCode_ERROR_CODE_ALREADY_EXISTS      ErrorCode = 4
	ErrorCode_ERROR_CODE_INTERNAL            ErrorCode = 5
	ErrorCode_ERROR_CODE_UNAVAILABLE         ErrorCode = 6
	ErrorCode_ERROR_CODE_DEADLINE_EXCEEDED   ErrorCode = 7
	ErrorCode_ERROR_CODE_CANCELLED           ErrorCode = 8
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0: "ERROR_CODE_UNSPECIFIED",
		1: "ERROR_CODE_INVALID_ARGUMENT",
		2: "ERROR_CODE_NOT_FOUND",
		3: "ERROR_CODE_FAILED_PRECONDITION",
		4: "ERROR_CODE_ALREADY_EXISTS",
		5: "ERROR_CODE_INTERNAL",
		6: "ERROR_CODE_UNAVAILABLE",
		7: "ERROR_CODE_DEADLINE_EXCEEDED",
		8: "ERROR_CODE_CANCELLED",
	}
	ErrorCode_value = map[string]int32{
		"ERROR_CODE_UNSPECIFIED":         0,
		"ERROR_CODE_INVALID_ARGUMENT":    1,
		"ERROR_CODE_NOT_FOUND":           2,
		"ERROR_CODE_FAILED_PRECONDITION": 3,
		"ERROR_CODE_ALREADY_EXISTS":      4,
		"ERROR_CODE_INTERNAL":            5,
		"ERROR_CODE_UNAVAILABLE":         6,
		"ERROR_CODE_DEADLINE_EXCEEDED":   7,
		"ERROR_CODE_CANCELLED":           8,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_common_v1_errors_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_common_v1_errors_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_common_v1_errors_proto_rawDescGZIP(), []int{0}
}

var File_common_v1_errors_proto protoreflect.FileDescriptor

const file_common_v1_errors_proto_rawDesc = "" +
	"\n" +
	"\x16common/v1/errors.proto\x12\tcommon.v1*\x96\x02\n" +
	"\tErrorCode\x12\x1a\n" +
	"\x16ERROR_CODE_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bERROR_CODE_INVALID_ARGUMENT\x10\x01\x12\x18\n" +
	"\x14ERROR_CODE_NOT_FOUND\x10\x02\x12\"\n" +
	"\x1eERROR_CODE_FAILED_PRECONDITION\x10\x03\x12\x1d\n" +
	"\x19ERROR_CODE_ALREADY_EXISTS\x10\x04\x12\x17\n" +
	"\x13ERROR_CODE_INTERNAL\x10\x05\x12\x1a\n" +
	"\x16ERROR_CODE_UNAVAILABLE\x10\x06\x12 \n" +
	"\x1cERROR_CODE_DEADLINE_EXCEEDED\x10\a\x12\x18\n" +
	"\x14ERROR_CODE_CANCELLED\x10\bB/Z-piper_agent/runtime/pkg/pb/common/v1;commonv1b\x06proto3"

var (
	file_common_v1_errors_proto_rawDescOnce sync.Once
	file_common_v1_errors_proto_rawDescData []byte
)

func file_common_v1_errors_proto_rawDescGZIP() []byte {
	file_common_v1_errors_proto_rawDescOnce.Do(func() {
		file_common_v1_errors_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_v1_errors_proto_rawDesc), len(file_common_v1_errors_proto_rawDesc)))
	})
	return file_common_v1_errors_proto_rawDescData
}

var file_common_v1_errors_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_common_v1_errors_proto_goTypes = []any{
	(ErrorCode)(0), // 0: common.v1.ErrorCode
}
var file_common_v1_errors_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_v1_errors_proto_init() }
func file_common_v1_errors_proto_init() {
	if File_common_v1_errors_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_v1_errors_proto_rawDesc), len(file_common_v1_errors_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_v1_errors_proto_goTypes,
		DependencyIndexes: file_common_v1_errors_proto_depIdxs,
		EnumInfos:         file_common_v1_errors_proto_enumTypes,
	}.Build()
	File_common_v1_errors_proto = out.File
	file_common_v1_errors_proto_goTypes = nil
	file_common_v1_errors_proto_depIdxs = nil
}
