// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: common/v1/types.proto

package commonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RunPhase int32

const (
	RunPhase_RUN_PHASE_UNSPECIFIED RunPhase = 0
	RunPhase_RUN_PHASE_VALIDATED   RunPhase = 1
	RunPhase_RUN_PHASE_RUNNING     RunPhase = 2
	RunPhase_RUN_PHASE_SUCCEEDED   RunPhase = 3
	RunPhase_RUN_PHASE_FAILED      RunPhase = 4
	RunPhase_RUN_PHASE_CANCELLED   RunPhase = 5
)

// Enum value maps for RunPhase.
var (
	RunPhase_name = map[int32]string{
		0: "RUN_PHASE_UNSPECIFIED",
		1: "RUN_PHASE_VALIDATED",
		2: "RUN_PHASE_RUNNING",
		3: "RUN_PHASE_SUCCEEDED",
		4: "RUN_PHASE_FAILED",
		5: "RUN_PHASE_CANCELLED",
	}
	RunPhase_value = map[string]int32{
		"RUN_PHASE_UNSPECIFIED": 0,
		"RUN_PHASE_VALIDATED":   1,
		"RUN_PHASE_RUNNING":     2,
		"RUN_PHASE_SUCCEEDED":   3,
		"RUN_PHASE_FAILED":      4,
		"RUN_PHASE_CANCELLED":   5,
	}
)

func (x RunPhase) Enum() *RunPhase {
	p := new(RunPhase)
	*p = x
	return p
}

func (x RunPhase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RunPhase) Descriptor() protoreflect.EnumDescriptor {
	return file_common_v1_types_proto_enumTypes[0].Descriptor()
}

func (RunPhase) Type() protoreflect.EnumType {
	return &file_common_v1_types_proto_enumTypes[0]
}

func (x RunPhase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RunPhase.Descriptor instead.
func (RunPhase) EnumDescriptor() ([]byte, []int) {
	return file_common_v1_types_proto_rawDescGZIP(), []int{0}
}

// TemplateDoc mirrors Piper meta `templates` row JSON (builder + procedures).
type TemplateDoc struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Domain        string                 `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain,omitempty"`
	JsonPayload   []byte                 `protobuf:"bytes,4,opt,name=json_payload,json=jsonPayload,proto3" json:"json_payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TemplateDoc) Reset() {
	*x = TemplateDoc{}
	mi := &file_common_v1_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemplateDoc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateDoc) ProtoMessage() {}

func (x *TemplateDoc) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateDoc.ProtoReflect.Descriptor instead.
func (*TemplateDoc) Descriptor() ([]byte, []int) {
	return file_common_v1_types_proto_rawDescGZIP(), []int{0}
}

func (x *TemplateDoc) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TemplateDoc) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TemplateDoc) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *TemplateDoc) GetJsonPayload() []byte {
	if x != nil {
		return x.JsonPayload
	}
	return nil
}

type Vars struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        map[string]string      `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vars) Reset() {
	*x = Vars{}
	mi := &file_common_v1_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vars) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vars) ProtoMessage() {}

func (x *Vars) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vars.ProtoReflect.Descriptor instead.
func (*Vars) Descriptor() ([]byte, []int) {
	return file_common_v1_types_proto_rawDescGZIP(), []int{1}
}

func (x *Vars) GetValues() map[string]string {
	if x != nil {
		return x.Values
	}
	return nil
}

type Diagnostic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Diagnostic) Reset() {
	*x = Diagnostic{}
	mi := &file_common_v1_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Diagnostic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Diagnostic) ProtoMessage() {}

func (x *Diagnostic) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Diagnostic.ProtoReflect.Descriptor instead.
func (*Diagnostic) Descriptor() ([]byte, []int) {
	return file_common_v1_types_proto_rawDescGZIP(), []int{2}
}

func (x *Diagnostic) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Diagnostic) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Diagnostic) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type RunStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Phase         RunPhase               `protobuf:"varint,3,opt,name=phase,proto3,enum=common.v1.RunPhase" json:"phase,omitempty"`
	TokenId       string                 `protobuf:"bytes,4,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	Diagnostics   []*Diagnostic          `protobuf:"bytes,5,rep,name=diagnostics,proto3" json:"diagnostics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunStatus) Reset() {
	*x = RunStatus{}
	mi := &file_common_v1_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunStatus) ProtoMessage() {}

func (x *RunStatus) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunStatus.ProtoReflect.Descriptor instead.
func (*RunStatus) Descriptor() ([]byte, []int) {
	return file_common_v1_types_proto_rawDescGZIP(), []int{3}
}

func (x *RunStatus) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *RunStatus) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RunStatus) GetPhase() RunPhase {
	if x != nil {
		return x.Phase
	}
	return RunPhase_RUN_PHASE_UNSPECIFIED
}

func (x *RunStatus) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

func (x *RunStatus) GetDiagnostics() []*Diagnostic {
	if x != nil {
		return x.Diagnostics
	}
	return nil
}

var File_common_v1_types_proto protoreflect.FileDescriptor

const file_common_v1_types_proto_rawDesc = "" +
	"\n" +
	"\x15common/v1/types.proto\x12\tcommon.v1\"l\n" +
	"\vTemplateDoc\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06domain\x18\x03 \x01(\tR\x06domain\x12!\n" +
	"\fjson_payload\x18\x04 \x01(\fR\vjsonPayload\"v\n" +
	"\x04Vars\x123\n" +
	"\x06values\x18\x01 \x03(\v2\x1b.common.v1.Vars.ValuesEntryR\x06values\x1a9\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"N\n" +
	"\n" +
	"Diagnostic\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\"\xc0\x01\n" +
	"\tRunStatus\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12)\n" +
	"\x05phase\x18\x03 \x01(\x0e2\x13.common.v1.RunPhaseR\x05phase\x12\x19\n" +
	"\btoken_id\x18\x04 \x01(\tR\atokenId\x127\n" +
	"\vdiagnostics\x18\x05 \x03(\v2\x15.common.v1.DiagnosticR\vdiagnostics*\x9d\x01\n" +
	"\bRunPhase\x12\x19\n" +
	"\x15RUN_PHASE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13RUN_PHASE_VALIDATED\x10\x01\x12\x15\n" +
	"\x11RUN_PHASE_RUNNING\x10\x02\x12\x17\n" +
	"\x13RUN_PHASE_SUCCEEDED\x10\x03\x12\x14\n" +
	"\x10RUN_PHASE_FAILED\x10\x04\x12\x17\n" +
	"\x13RUN_PHASE_CANCELLED\x10\x05B/Z-piper_agent/runtime/pkg/pb/common/v1;commonv1b\x06proto3"

var (
	file_common_v1_types_proto_rawDescOnce sync.Once
	file_common_v1_types_proto_rawDescData []byte
)

func file_common_v1_types_proto_rawDescGZIP() []byte {
	file_common_v1_types_proto_rawDescOnce.Do(func() {
		file_common_v1_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_v1_types_proto_rawDesc), len(file_common_v1_types_proto_rawDesc)))
	})
	return file_common_v1_types_proto_rawDescData
}

var file_common_v1_types_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_common_v1_types_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_common_v1_types_proto_goTypes = []any{
	(RunPhase)(0),       // 0: common.v1.RunPhase
	(*TemplateDoc)(nil), // 1: common.v1.TemplateDoc
	(*Vars)(nil),        // 2: common.v1.Vars
	(*Diagnostic)(nil),  // 3: common.v1.Diagnostic
	(*RunStatus)(nil),   // 4: common.v1.RunStatus
	nil,                 // 5: common.v1.Vars.ValuesEntry
}
var file_common_v1_types_proto_depIdxs = []int32{
	5, // 0: common.v1.Vars.values:type_name -> common.v1.Vars.ValuesEntry
	0, // 1: common.v1.RunStatus.phase:type_name -> common.v1.RunPhase
	3, // 2: common.v1.RunStatus.diagnostics:type_name -> common.v1.Diagnostic
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_common_v1_types_proto_init() }
func file_common_v1_types_proto_init() {
	if File_common_v1_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_v1_types_proto_rawDesc), len(file_common_v1_types_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_v1_types_proto_goTypes,
		DependencyIndexes: file_common_v1_types_proto_depIdxs,
		EnumInfos:         file_common_v1_types_proto_enumTypes,
		MessageInfos:      file_common_v1_types_proto_msgTypes,
	}.Build()
	File_common_v1_types_proto = out.File
	file_common_v1_types_proto_goTypes = nil
	file_common_v1_types_proto_depIdxs = nil
}
