# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: runtime/v1/execute.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'runtime/v1/execute.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from web_crawler_agent.pb.common.v1 import types_pb2 as common_dot_v1_dot_types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18runtime/v1/execute.proto\x12\nruntime.v1\x1a\x15\x63ommon/v1/types.proto\"\xab\x01\n\x12RunTemplateRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x12\n\nsession_id\x18\x02 \x01(\t\x12\x17\n\x0fidempotency_key\x18\x03 \x01(\t\x12\x13\n\x0btemplate_id\x18\x04 \x01(\t\x12\x1d\n\x04vars\x18\x05 \x01(\x0b\x32\x0f.common.v1.Vars\x12\x10\n\x08proxy_id\x18\x06 \x01(\t\x12\x0e\n\x06\x65ngine\x18\x07 \x01(\t\"K\n\x13RunTemplateResponse\x12\x0e\n\x06run_id\x18\x01 \x01(\t\x12$\n\x06status\x18\x02 \x01(\x0b\x32\x14.common.v1.RunStatus\"6\n\x10\x43\x61ncelRunRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x0e\n\x06run_id\x18\x02 \x01(\t\"\x13\n\x11\x43\x61ncelRunResponse\"9\n\x13SubscribeRunRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x0e\n\x06run_id\x18\x02 \x01(\t\"A\n\x08RunEvent\x12$\n\x06status\x18\x01 \x01(\x0b\x32\x14.common.v1.RunStatus\x12\x0f\n\x07message\x18\x02 \x01(\t2\xf3\x01\n\x0eRuntimeExecute\x12N\n\x0bRunTemplate\x12\x1e.runtime.v1.RunTemplateRequest\x1a\x1f.runtime.v1.RunTemplateResponse\x12H\n\tCancelRun\x12\x1c.runtime.v1.CancelRunRequest\x1a\x1d.runtime.v1.CancelRunResponse\x12G\n\x0cSubscribeRun\x12\x1f.runtime.v1.SubscribeRunRequest\x1a\x14.runtime.v1.RunEvent0\x01\x42\x31Z/piper_agent/runtime/pkg/pb/runtime/v1;runtimev1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'runtime.v1.execute_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z/piper_agent/runtime/pkg/pb/runtime/v1;runtimev1'
  _globals['_RUNTEMPLATEREQUEST']._serialized_start=64
  _globals['_RUNTEMPLATEREQUEST']._serialized_end=235
  _globals['_RUNTEMPLATERESPONSE']._serialized_start=237
  _globals['_RUNTEMPLATERESPONSE']._serialized_end=312
  _globals['_CANCELRUNREQUEST']._serialized_start=314
  _globals['_CANCELRUNREQUEST']._serialized_end=368
  _globals['_CANCELRUNRESPONSE']._serialized_start=370
  _globals['_CANCELRUNRESPONSE']._serialized_end=389
  _globals['_SUBSCRIBERUNREQUEST']._serialized_start=391
  _globals['_SUBSCRIBERUNREQUEST']._serialized_end=448
  _globals['_RUNEVENT']._serialized_start=450
  _globals['_RUNEVENT']._serialized_end=515
  _globals['_RUNTIMEEXECUTE']._serialized_start=518
  _globals['_RUNTIMEEXECUTE']._serialized_end=761
# @@protoc_insertion_point(module_scope)
