# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common/v1/types.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'common/v1/types.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x63ommon/v1/types.proto\x12\tcommon.v1\"M\n\x0bTemplateDoc\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06\x64omain\x18\x03 \x01(\t\x12\x14\n\x0cjson_payload\x18\x04 \x01(\x0c\"b\n\x04Vars\x12+\n\x06values\x18\x01 \x03(\x0b\x32\x1b.common.v1.Vars.ValuesEntry\x1a-\n\x0bValuesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"9\n\nDiagnostic\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0c\n\x04path\x18\x03 \x01(\t\"\x91\x01\n\tRunStatus\x12\x0e\n\x06run_id\x18\x01 \x01(\t\x12\x12\n\nsession_id\x18\x02 \x01(\t\x12\"\n\x05phase\x18\x03 \x01(\x0e\x32\x13.common.v1.RunPhase\x12\x10\n\x08token_id\x18\x04 \x01(\t\x12*\n\x0b\x64iagnostics\x18\x05 \x03(\x0b\x32\x15.common.v1.Diagnostic*\x9d\x01\n\x08RunPhase\x12\x19\n\x15RUN_PHASE_UNSPECIFIED\x10\x00\x12\x17\n\x13RUN_PHASE_VALIDATED\x10\x01\x12\x15\n\x11RUN_PHASE_RUNNING\x10\x02\x12\x17\n\x13RUN_PHASE_SUCCEEDED\x10\x03\x12\x14\n\x10RUN_PHASE_FAILED\x10\x04\x12\x17\n\x13RUN_PHASE_CANCELLED\x10\x05\x42/Z-piper_agent/runtime/pkg/pb/common/v1;commonv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common.v1.types_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z-piper_agent/runtime/pkg/pb/common/v1;commonv1'
  _globals['_VARS_VALUESENTRY']._loaded_options = None
  _globals['_VARS_VALUESENTRY']._serialized_options = b'8\001'
  _globals['_RUNPHASE']._serialized_start=423
  _globals['_RUNPHASE']._serialized_end=580
  _globals['_TEMPLATEDOC']._serialized_start=36
  _globals['_TEMPLATEDOC']._serialized_end=113
  _globals['_VARS']._serialized_start=115
  _globals['_VARS']._serialized_end=213
  _globals['_VARS_VALUESENTRY']._serialized_start=168
  _globals['_VARS_VALUESENTRY']._serialized_end=213
  _globals['_DIAGNOSTIC']._serialized_start=215
  _globals['_DIAGNOSTIC']._serialized_end=272
  _globals['_RUNSTATUS']._serialized_start=275
  _globals['_RUNSTATUS']._serialized_end=420
# @@protoc_insertion_point(module_scope)
