// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.20.3
// source: runtime/v1/execute.proto

package runtimev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RuntimeExecute_RunTemplate_FullMethodName  = "/runtime.v1.RuntimeExecute/RunTemplate"
	RuntimeExecute_CancelRun_FullMethodName    = "/runtime.v1.RuntimeExecute/CancelRun"
	RuntimeExecute_SubscribeRun_FullMethodName = "/runtime.v1.RuntimeExecute/SubscribeRun"
)

// RuntimeExecuteClient is the client API for RuntimeExecute service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RuntimeExecuteClient interface {
	RunTemplate(ctx context.Context, in *RunTemplateRequest, opts ...grpc.CallOption) (*RunTemplateResponse, error)
	CancelRun(ctx context.Context, in *CancelRunRequest, opts ...grpc.CallOption) (*CancelRunResponse, error)
	SubscribeRun(ctx context.Context, in *SubscribeRunRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RunEvent], error)
}

type runtimeExecuteClient struct {
	cc grpc.ClientConnInterface
}

func NewRuntimeExecuteClient(cc grpc.ClientConnInterface) RuntimeExecuteClient {
	return &runtimeExecuteClient{cc}
}

func (c *runtimeExecuteClient) RunTemplate(ctx context.Context, in *RunTemplateRequest, opts ...grpc.CallOption) (*RunTemplateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunTemplateResponse)
	err := c.cc.Invoke(ctx, RuntimeExecute_RunTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeExecuteClient) CancelRun(ctx context.Context, in *CancelRunRequest, opts ...grpc.CallOption) (*CancelRunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelRunResponse)
	err := c.cc.Invoke(ctx, RuntimeExecute_CancelRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeExecuteClient) SubscribeRun(ctx context.Context, in *SubscribeRunRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RunEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RuntimeExecute_ServiceDesc.Streams[0], RuntimeExecute_SubscribeRun_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRunRequest, RunEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RuntimeExecute_SubscribeRunClient = grpc.ServerStreamingClient[RunEvent]

// RuntimeExecuteServer is the server API for RuntimeExecute service.
// All implementations must embed UnimplementedRuntimeExecuteServer
// for forward compatibility.
type RuntimeExecuteServer interface {
	RunTemplate(context.Context, *RunTemplateRequest) (*RunTemplateResponse, error)
	CancelRun(context.Context, *CancelRunRequest) (*CancelRunResponse, error)
	SubscribeRun(*SubscribeRunRequest, grpc.ServerStreamingServer[RunEvent]) error
	mustEmbedUnimplementedRuntimeExecuteServer()
}

// UnimplementedRuntimeExecuteServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRuntimeExecuteServer struct{}

func (UnimplementedRuntimeExecuteServer) RunTemplate(context.Context, *RunTemplateRequest) (*RunTemplateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RunTemplate not implemented")
}
func (UnimplementedRuntimeExecuteServer) CancelRun(context.Context, *CancelRunRequest) (*CancelRunResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelRun not implemented")
}
func (UnimplementedRuntimeExecuteServer) SubscribeRun(*SubscribeRunRequest, grpc.ServerStreamingServer[RunEvent]) error {
	return status.Error(codes.Unimplemented, "method SubscribeRun not implemented")
}
func (UnimplementedRuntimeExecuteServer) mustEmbedUnimplementedRuntimeExecuteServer() {}
func (UnimplementedRuntimeExecuteServer) testEmbeddedByValue()                        {}

// UnsafeRuntimeExecuteServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RuntimeExecuteServer will
// result in compilation errors.
type UnsafeRuntimeExecuteServer interface {
	mustEmbedUnimplementedRuntimeExecuteServer()
}

func RegisterRuntimeExecuteServer(s grpc.ServiceRegistrar, srv RuntimeExecuteServer) {
	// If the following call panics, it indicates UnimplementedRuntimeExecuteServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RuntimeExecute_ServiceDesc, srv)
}

func _RuntimeExecute_RunTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeExecuteServer).RunTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeExecute_RunTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeExecuteServer).RunTemplate(ctx, req.(*RunTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeExecute_CancelRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeExecuteServer).CancelRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeExecute_CancelRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeExecuteServer).CancelRun(ctx, req.(*CancelRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeExecute_SubscribeRun_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRunRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RuntimeExecuteServer).SubscribeRun(m, &grpc.GenericServerStream[SubscribeRunRequest, RunEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RuntimeExecute_SubscribeRunServer = grpc.ServerStreamingServer[RunEvent]

// RuntimeExecute_ServiceDesc is the grpc.ServiceDesc for RuntimeExecute service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RuntimeExecute_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "runtime.v1.RuntimeExecute",
	HandlerType: (*RuntimeExecuteServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RunTemplate",
			Handler:    _RuntimeExecute_RunTemplate_Handler,
		},
		{
			MethodName: "CancelRun",
			Handler:    _RuntimeExecute_CancelRun_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeRun",
			Handler:       _RuntimeExecute_SubscribeRun_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "runtime/v1/execute.proto",
}
