// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: runtime/v1/meta.proto

package runtimev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	v1 "piper_agent/runtime/pkg/pb/common/v1"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListTemplatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Query         string                 `protobuf:"bytes,4,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTemplatesRequest) Reset() {
	*x = ListTemplatesRequest{}
	mi := &file_runtime_v1_meta_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTemplatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTemplatesRequest) ProtoMessage() {}

func (x *ListTemplatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_meta_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTemplatesRequest.ProtoReflect.Descriptor instead.
func (*ListTemplatesRequest) Descriptor() ([]byte, []int) {
	return file_runtime_v1_meta_proto_rawDescGZIP(), []int{0}
}

func (x *ListTemplatesRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ListTemplatesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListTemplatesRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ListTemplatesRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type ListTemplatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Templates     []*v1.TemplateDoc      `protobuf:"bytes,1,rep,name=templates,proto3" json:"templates,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTemplatesResponse) Reset() {
	*x = ListTemplatesResponse{}
	mi := &file_runtime_v1_meta_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTemplatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTemplatesResponse) ProtoMessage() {}

func (x *ListTemplatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_meta_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTemplatesResponse.ProtoReflect.Descriptor instead.
func (*ListTemplatesResponse) Descriptor() ([]byte, []int) {
	return file_runtime_v1_meta_proto_rawDescGZIP(), []int{1}
}

func (x *ListTemplatesResponse) GetTemplates() []*v1.TemplateDoc {
	if x != nil {
		return x.Templates
	}
	return nil
}

func (x *ListTemplatesResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	TemplateId    string                 `protobuf:"bytes,2,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTemplateRequest) Reset() {
	*x = GetTemplateRequest{}
	mi := &file_runtime_v1_meta_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTemplateRequest) ProtoMessage() {}

func (x *GetTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_meta_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTemplateRequest.ProtoReflect.Descriptor instead.
func (*GetTemplateRequest) Descriptor() ([]byte, []int) {
	return file_runtime_v1_meta_proto_rawDescGZIP(), []int{2}
}

func (x *GetTemplateRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *GetTemplateRequest) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

type GetTemplateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Template      *v1.TemplateDoc        `protobuf:"bytes,1,opt,name=template,proto3" json:"template,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTemplateResponse) Reset() {
	*x = GetTemplateResponse{}
	mi := &file_runtime_v1_meta_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTemplateResponse) ProtoMessage() {}

func (x *GetTemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_meta_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTemplateResponse.ProtoReflect.Descriptor instead.
func (*GetTemplateResponse) Descriptor() ([]byte, []int) {
	return file_runtime_v1_meta_proto_rawDescGZIP(), []int{3}
}

func (x *GetTemplateResponse) GetTemplate() *v1.TemplateDoc {
	if x != nil {
		return x.Template
	}
	return nil
}

type ProxyDoc struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Domain        string                 `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyDoc) Reset() {
	*x = ProxyDoc{}
	mi := &file_runtime_v1_meta_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyDoc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyDoc) ProtoMessage() {}

func (x *ProxyDoc) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_meta_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyDoc.ProtoReflect.Descriptor instead.
func (*ProxyDoc) Descriptor() ([]byte, []int) {
	return file_runtime_v1_meta_proto_rawDescGZIP(), []int{4}
}

func (x *ProxyDoc) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProxyDoc) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProxyDoc) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *ProxyDoc) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListProxiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProxiesRequest) Reset() {
	*x = ListProxiesRequest{}
	mi := &file_runtime_v1_meta_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProxiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProxiesRequest) ProtoMessage() {}

func (x *ListProxiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_meta_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProxiesRequest.ProtoReflect.Descriptor instead.
func (*ListProxiesRequest) Descriptor() ([]byte, []int) {
	return file_runtime_v1_meta_proto_rawDescGZIP(), []int{5}
}

func (x *ListProxiesRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ListProxiesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListProxiesRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ListProxiesRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListProxiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Proxies       []*ProxyDoc            `protobuf:"bytes,1,rep,name=proxies,proto3" json:"proxies,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProxiesResponse) Reset() {
	*x = ListProxiesResponse{}
	mi := &file_runtime_v1_meta_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProxiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProxiesResponse) ProtoMessage() {}

func (x *ListProxiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_meta_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProxiesResponse.ProtoReflect.Descriptor instead.
func (*ListProxiesResponse) Descriptor() ([]byte, []int) {
	return file_runtime_v1_meta_proto_rawDescGZIP(), []int{6}
}

func (x *ListProxiesResponse) GetProxies() []*ProxyDoc {
	if x != nil {
		return x.Proxies
	}
	return nil
}

func (x *ListProxiesResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_runtime_v1_meta_proto protoreflect.FileDescriptor

const file_runtime_v1_meta_proto_rawDesc = "" +
	"\n" +
	"\x15runtime/v1/meta.proto\x12\n" +
	"runtime.v1\x1a\x15common/v1/types.proto\"s\n" +
	"\x14ListTemplatesRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x05R\x04size\x12\x14\n" +
	"\x05query\x18\x04 \x01(\tR\x05query\"c\n" +
	"\x15ListTemplatesResponse\x124\n" +
	"\ttemplates\x18\x01 \x03(\v2\x16.common.v1.TemplateDocR\ttemplates\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"T\n" +
	"\x12GetTemplateRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1f\n" +
	"\vtemplate_id\x18\x02 \x01(\tR\n" +
	"templateId\"I\n" +
	"\x13GetTemplateResponse\x122\n" +
	"\btemplate\x18\x01 \x01(\v2\x16.common.v1.TemplateDocR\btemplate\"^\n" +
	"\bProxyDoc\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06domain\x18\x03 \x01(\tR\x06domain\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"s\n" +
	"\x12ListProxiesRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x05R\x04size\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"[\n" +
	"\x13ListProxiesResponse\x12.\n" +
	"\aproxies\x18\x01 \x03(\v2\x14.runtime.v1.ProxyDocR\aproxies\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total2\x83\x02\n" +
	"\vRuntimeMeta\x12T\n" +
	"\rListTemplates\x12 .runtime.v1.ListTemplatesRequest\x1a!.runtime.v1.ListTemplatesResponse\x12N\n" +
	"\vGetTemplate\x12\x1e.runtime.v1.GetTemplateRequest\x1a\x1f.runtime.v1.GetTemplateResponse\x12N\n" +
	"\vListProxies\x12\x1e.runtime.v1.ListProxiesRequest\x1a\x1f.runtime.v1.ListProxiesResponseB1Z/piper_agent/runtime/pkg/pb/runtime/v1;runtimev1b\x06proto3"

var (
	file_runtime_v1_meta_proto_rawDescOnce sync.Once
	file_runtime_v1_meta_proto_rawDescData []byte
)

func file_runtime_v1_meta_proto_rawDescGZIP() []byte {
	file_runtime_v1_meta_proto_rawDescOnce.Do(func() {
		file_runtime_v1_meta_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_runtime_v1_meta_proto_rawDesc), len(file_runtime_v1_meta_proto_rawDesc)))
	})
	return file_runtime_v1_meta_proto_rawDescData
}

var file_runtime_v1_meta_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_runtime_v1_meta_proto_goTypes = []any{
	(*ListTemplatesRequest)(nil),  // 0: runtime.v1.ListTemplatesRequest
	(*ListTemplatesResponse)(nil), // 1: runtime.v1.ListTemplatesResponse
	(*GetTemplateRequest)(nil),    // 2: runtime.v1.GetTemplateRequest
	(*GetTemplateResponse)(nil),   // 3: runtime.v1.GetTemplateResponse
	(*ProxyDoc)(nil),              // 4: runtime.v1.ProxyDoc
	(*ListProxiesRequest)(nil),    // 5: runtime.v1.ListProxiesRequest
	(*ListProxiesResponse)(nil),   // 6: runtime.v1.ListProxiesResponse
	(*v1.TemplateDoc)(nil),        // 7: common.v1.TemplateDoc
}
var file_runtime_v1_meta_proto_depIdxs = []int32{
	7, // 0: runtime.v1.ListTemplatesResponse.templates:type_name -> common.v1.TemplateDoc
	7, // 1: runtime.v1.GetTemplateResponse.template:type_name -> common.v1.TemplateDoc
	4, // 2: runtime.v1.ListProxiesResponse.proxies:type_name -> runtime.v1.ProxyDoc
	0, // 3: runtime.v1.RuntimeMeta.ListTemplates:input_type -> runtime.v1.ListTemplatesRequest
	2, // 4: runtime.v1.RuntimeMeta.GetTemplate:input_type -> runtime.v1.GetTemplateRequest
	5, // 5: runtime.v1.RuntimeMeta.ListProxies:input_type -> runtime.v1.ListProxiesRequest
	1, // 6: runtime.v1.RuntimeMeta.ListTemplates:output_type -> runtime.v1.ListTemplatesResponse
	3, // 7: runtime.v1.RuntimeMeta.GetTemplate:output_type -> runtime.v1.GetTemplateResponse
	6, // 8: runtime.v1.RuntimeMeta.ListProxies:output_type -> runtime.v1.ListProxiesResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_runtime_v1_meta_proto_init() }
func file_runtime_v1_meta_proto_init() {
	if File_runtime_v1_meta_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_runtime_v1_meta_proto_rawDesc), len(file_runtime_v1_meta_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_runtime_v1_meta_proto_goTypes,
		DependencyIndexes: file_runtime_v1_meta_proto_depIdxs,
		MessageInfos:      file_runtime_v1_meta_proto_msgTypes,
	}.Build()
	File_runtime_v1_meta_proto = out.File
	file_runtime_v1_meta_proto_goTypes = nil
	file_runtime_v1_meta_proto_depIdxs = nil
}
