// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: runtime/v1/template.proto

package runtimev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	v1 "piper_agent/runtime/pkg/pb/common/v1"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValidateTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Template      *v1.TemplateDoc        `protobuf:"bytes,2,opt,name=template,proto3" json:"template,omitempty"`
	TemplateId    string                 `protobuf:"bytes,3,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	Vars          *v1.Vars               `protobuf:"bytes,4,opt,name=vars,proto3" json:"vars,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTemplateRequest) Reset() {
	*x = ValidateTemplateRequest{}
	mi := &file_runtime_v1_template_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTemplateRequest) ProtoMessage() {}

func (x *ValidateTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_template_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTemplateRequest.ProtoReflect.Descriptor instead.
func (*ValidateTemplateRequest) Descriptor() ([]byte, []int) {
	return file_runtime_v1_template_proto_rawDescGZIP(), []int{0}
}

func (x *ValidateTemplateRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ValidateTemplateRequest) GetTemplate() *v1.TemplateDoc {
	if x != nil {
		return x.Template
	}
	return nil
}

func (x *ValidateTemplateRequest) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *ValidateTemplateRequest) GetVars() *v1.Vars {
	if x != nil {
		return x.Vars
	}
	return nil
}

type ValidateTemplateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Diagnostics   []*v1.Diagnostic       `protobuf:"bytes,2,rep,name=diagnostics,proto3" json:"diagnostics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTemplateResponse) Reset() {
	*x = ValidateTemplateResponse{}
	mi := &file_runtime_v1_template_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTemplateResponse) ProtoMessage() {}

func (x *ValidateTemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_template_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTemplateResponse.ProtoReflect.Descriptor instead.
func (*ValidateTemplateResponse) Descriptor() ([]byte, []int) {
	return file_runtime_v1_template_proto_rawDescGZIP(), []int{1}
}

func (x *ValidateTemplateResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ValidateTemplateResponse) GetDiagnostics() []*v1.Diagnostic {
	if x != nil {
		return x.Diagnostics
	}
	return nil
}

type UpsertTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Template      *v1.TemplateDoc        `protobuf:"bytes,2,opt,name=template,proto3" json:"template,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertTemplateRequest) Reset() {
	*x = UpsertTemplateRequest{}
	mi := &file_runtime_v1_template_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertTemplateRequest) ProtoMessage() {}

func (x *UpsertTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_template_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertTemplateRequest.ProtoReflect.Descriptor instead.
func (*UpsertTemplateRequest) Descriptor() ([]byte, []int) {
	return file_runtime_v1_template_proto_rawDescGZIP(), []int{2}
}

func (x *UpsertTemplateRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *UpsertTemplateRequest) GetTemplate() *v1.TemplateDoc {
	if x != nil {
		return x.Template
	}
	return nil
}

type UpsertTemplateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TemplateId    string                 `protobuf:"bytes,1,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertTemplateResponse) Reset() {
	*x = UpsertTemplateResponse{}
	mi := &file_runtime_v1_template_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertTemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertTemplateResponse) ProtoMessage() {}

func (x *UpsertTemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_template_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertTemplateResponse.ProtoReflect.Descriptor instead.
func (*UpsertTemplateResponse) Descriptor() ([]byte, []int) {
	return file_runtime_v1_template_proto_rawDescGZIP(), []int{3}
}

func (x *UpsertTemplateResponse) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

var File_runtime_v1_template_proto protoreflect.FileDescriptor

const file_runtime_v1_template_proto_rawDesc = "" +
	"\n" +
	"\x19runtime/v1/template.proto\x12\n" +
	"runtime.v1\x1a\x15common/v1/types.proto\"\xb2\x01\n" +
	"\x17ValidateTemplateRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x122\n" +
	"\btemplate\x18\x02 \x01(\v2\x16.common.v1.TemplateDocR\btemplate\x12\x1f\n" +
	"\vtemplate_id\x18\x03 \x01(\tR\n" +
	"templateId\x12#\n" +
	"\x04vars\x18\x04 \x01(\v2\x0f.common.v1.VarsR\x04vars\"c\n" +
	"\x18ValidateTemplateResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x127\n" +
	"\vdiagnostics\x18\x02 \x03(\v2\x15.common.v1.DiagnosticR\vdiagnostics\"j\n" +
	"\x15UpsertTemplateRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x122\n" +
	"\btemplate\x18\x02 \x01(\v2\x16.common.v1.TemplateDocR\btemplate\"9\n" +
	"\x16UpsertTemplateResponse\x12\x1f\n" +
	"\vtemplate_id\x18\x01 \x01(\tR\n" +
	"templateId2\xc9\x01\n" +
	"\x0fRuntimeTemplate\x12]\n" +
	"\x10ValidateTemplate\x12#.runtime.v1.ValidateTemplateRequest\x1a$.runtime.v1.ValidateTemplateResponse\x12W\n" +
	"\x0eUpsertTemplate\x12!.runtime.v1.UpsertTemplateRequest\x1a\".runtime.v1.UpsertTemplateResponseB1Z/piper_agent/runtime/pkg/pb/runtime/v1;runtimev1b\x06proto3"

var (
	file_runtime_v1_template_proto_rawDescOnce sync.Once
	file_runtime_v1_template_proto_rawDescData []byte
)

func file_runtime_v1_template_proto_rawDescGZIP() []byte {
	file_runtime_v1_template_proto_rawDescOnce.Do(func() {
		file_runtime_v1_template_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_runtime_v1_template_proto_rawDesc), len(file_runtime_v1_template_proto_rawDesc)))
	})
	return file_runtime_v1_template_proto_rawDescData
}

var file_runtime_v1_template_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_runtime_v1_template_proto_goTypes = []any{
	(*ValidateTemplateRequest)(nil),  // 0: runtime.v1.ValidateTemplateRequest
	(*ValidateTemplateResponse)(nil), // 1: runtime.v1.ValidateTemplateResponse
	(*UpsertTemplateRequest)(nil),    // 2: runtime.v1.UpsertTemplateRequest
	(*UpsertTemplateResponse)(nil),   // 3: runtime.v1.UpsertTemplateResponse
	(*v1.TemplateDoc)(nil),           // 4: common.v1.TemplateDoc
	(*v1.Vars)(nil),                  // 5: common.v1.Vars
	(*v1.Diagnostic)(nil),            // 6: common.v1.Diagnostic
}
var file_runtime_v1_template_proto_depIdxs = []int32{
	4, // 0: runtime.v1.ValidateTemplateRequest.template:type_name -> common.v1.TemplateDoc
	5, // 1: runtime.v1.ValidateTemplateRequest.vars:type_name -> common.v1.Vars
	6, // 2: runtime.v1.ValidateTemplateResponse.diagnostics:type_name -> common.v1.Diagnostic
	4, // 3: runtime.v1.UpsertTemplateRequest.template:type_name -> common.v1.TemplateDoc
	0, // 4: runtime.v1.RuntimeTemplate.ValidateTemplate:input_type -> runtime.v1.ValidateTemplateRequest
	2, // 5: runtime.v1.RuntimeTemplate.UpsertTemplate:input_type -> runtime.v1.UpsertTemplateRequest
	1, // 6: runtime.v1.RuntimeTemplate.ValidateTemplate:output_type -> runtime.v1.ValidateTemplateResponse
	3, // 7: runtime.v1.RuntimeTemplate.UpsertTemplate:output_type -> runtime.v1.UpsertTemplateResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_runtime_v1_template_proto_init() }
func file_runtime_v1_template_proto_init() {
	if File_runtime_v1_template_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_runtime_v1_template_proto_rawDesc), len(file_runtime_v1_template_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_runtime_v1_template_proto_goTypes,
		DependencyIndexes: file_runtime_v1_template_proto_depIdxs,
		MessageInfos:      file_runtime_v1_template_proto_msgTypes,
	}.Build()
	File_runtime_v1_template_proto = out.File
	file_runtime_v1_template_proto_goTypes = nil
	file_runtime_v1_template_proto_depIdxs = nil
}
