// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.20.3
// source: agent/v1/execute.proto

package agentv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentWorkerService_Execute_FullMethodName = "/agent.v1.AgentWorkerService/Execute"
	AgentWorkerService_Cancel_FullMethodName  = "/agent.v1.AgentWorkerService/Cancel"
	AgentWorkerService_Health_FullMethodName  = "/agent.v1.AgentWorkerService/Health"
)

// AgentWorkerServiceClient is the client API for AgentWorkerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Web 网关调用的 Python 子 Agent Worker（与 runtime.v1 采集 RPC 分离）。
type AgentWorkerServiceClient interface {
	Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecuteEvent], error)
	Cancel(ctx context.Context, in *CancelRequest, opts ...grpc.CallOption) (*CancelResponse, error)
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type agentWorkerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentWorkerServiceClient(cc grpc.ClientConnInterface) AgentWorkerServiceClient {
	return &agentWorkerServiceClient{cc}
}

func (c *agentWorkerServiceClient) Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecuteEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentWorkerService_ServiceDesc.Streams[0], AgentWorkerService_Execute_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecuteRequest, ExecuteEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentWorkerService_ExecuteClient = grpc.ServerStreamingClient[ExecuteEvent]

func (c *agentWorkerServiceClient) Cancel(ctx context.Context, in *CancelRequest, opts ...grpc.CallOption) (*CancelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelResponse)
	err := c.cc.Invoke(ctx, AgentWorkerService_Cancel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentWorkerServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, AgentWorkerService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentWorkerServiceServer is the server API for AgentWorkerService service.
// All implementations must embed UnimplementedAgentWorkerServiceServer
// for forward compatibility.
//
// Web 网关调用的 Python 子 Agent Worker（与 runtime.v1 采集 RPC 分离）。
type AgentWorkerServiceServer interface {
	Execute(*ExecuteRequest, grpc.ServerStreamingServer[ExecuteEvent]) error
	Cancel(context.Context, *CancelRequest) (*CancelResponse, error)
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedAgentWorkerServiceServer()
}

// UnimplementedAgentWorkerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentWorkerServiceServer struct{}

func (UnimplementedAgentWorkerServiceServer) Execute(*ExecuteRequest, grpc.ServerStreamingServer[ExecuteEvent]) error {
	return status.Error(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedAgentWorkerServiceServer) Cancel(context.Context, *CancelRequest) (*CancelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Cancel not implemented")
}
func (UnimplementedAgentWorkerServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedAgentWorkerServiceServer) mustEmbedUnimplementedAgentWorkerServiceServer() {}
func (UnimplementedAgentWorkerServiceServer) testEmbeddedByValue()                            {}

// UnsafeAgentWorkerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentWorkerServiceServer will
// result in compilation errors.
type UnsafeAgentWorkerServiceServer interface {
	mustEmbedUnimplementedAgentWorkerServiceServer()
}

func RegisterAgentWorkerServiceServer(s grpc.ServiceRegistrar, srv AgentWorkerServiceServer) {
	// If the following call panics, it indicates UnimplementedAgentWorkerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentWorkerService_ServiceDesc, srv)
}

func _AgentWorkerService_Execute_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExecuteRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentWorkerServiceServer).Execute(m, &grpc.GenericServerStream[ExecuteRequest, ExecuteEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentWorkerService_ExecuteServer = grpc.ServerStreamingServer[ExecuteEvent]

func _AgentWorkerService_Cancel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentWorkerServiceServer).Cancel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentWorkerService_Cancel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentWorkerServiceServer).Cancel(ctx, req.(*CancelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentWorkerService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentWorkerServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentWorkerService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentWorkerServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentWorkerService_ServiceDesc is the grpc.ServiceDesc for AgentWorkerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentWorkerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agent.v1.AgentWorkerService",
	HandlerType: (*AgentWorkerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Cancel",
			Handler:    _AgentWorkerService_Cancel_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _AgentWorkerService_Health_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Execute",
			Handler:       _AgentWorkerService_Execute_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "agent/v1/execute.proto",
}
