// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: agent/v1/execute.proto

package agentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 随聊天请求附带的原始文件（由网关 multipart 上传解析后转发给文档 RAG Worker）。
type UploadedDocument struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	MimeType      string                 `protobuf:"bytes,2,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadedDocument) Reset() {
	*x = UploadedDocument{}
	mi := &file_agent_v1_execute_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadedDocument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadedDocument) ProtoMessage() {}

func (x *UploadedDocument) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_execute_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadedDocument.ProtoReflect.Descriptor instead.
func (*UploadedDocument) Descriptor() ([]byte, []int) {
	return file_agent_v1_execute_proto_rawDescGZIP(), []int{0}
}

func (x *UploadedDocument) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *UploadedDocument) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *UploadedDocument) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ExecuteRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TraceId        string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	ConversationId string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	RunId          string                 `protobuf:"bytes,3,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	AgentId        string                 `protobuf:"bytes,4,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	UserMessage    string                 `protobuf:"bytes,5,opt,name=user_message,json=userMessage,proto3" json:"user_message,omitempty"`
	Documents      []*UploadedDocument    `protobuf:"bytes,6,rep,name=documents,proto3" json:"documents,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_agent_v1_execute_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_execute_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_execute_proto_rawDescGZIP(), []int{1}
}

func (x *ExecuteRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *ExecuteRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ExecuteRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *ExecuteRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ExecuteRequest) GetUserMessage() string {
	if x != nil {
		return x.UserMessage
	}
	return ""
}

func (x *ExecuteRequest) GetDocuments() []*UploadedDocument {
	if x != nil {
		return x.Documents
	}
	return nil
}

type ExecuteEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Delta         string                 `protobuf:"bytes,2,opt,name=delta,proto3" json:"delta,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	ToolName      string                 `protobuf:"bytes,4,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	ToolDetail    string                 `protobuf:"bytes,5,opt,name=tool_detail,json=toolDetail,proto3" json:"tool_detail,omitempty"`
	Message       string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteEvent) Reset() {
	*x = ExecuteEvent{}
	mi := &file_agent_v1_execute_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteEvent) ProtoMessage() {}

func (x *ExecuteEvent) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_execute_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteEvent.ProtoReflect.Descriptor instead.
func (*ExecuteEvent) Descriptor() ([]byte, []int) {
	return file_agent_v1_execute_proto_rawDescGZIP(), []int{2}
}

func (x *ExecuteEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ExecuteEvent) GetDelta() string {
	if x != nil {
		return x.Delta
	}
	return ""
}

func (x *ExecuteEvent) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ExecuteEvent) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ExecuteEvent) GetToolDetail() string {
	if x != nil {
		return x.ToolDetail
	}
	return ""
}

func (x *ExecuteEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CancelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRequest) Reset() {
	*x = CancelRequest{}
	mi := &file_agent_v1_execute_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRequest) ProtoMessage() {}

func (x *CancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_execute_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRequest.ProtoReflect.Descriptor instead.
func (*CancelRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_execute_proto_rawDescGZIP(), []int{3}
}

func (x *CancelRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type CancelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelResponse) Reset() {
	*x = CancelResponse{}
	mi := &file_agent_v1_execute_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelResponse) ProtoMessage() {}

func (x *CancelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_execute_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelResponse.ProtoReflect.Descriptor instead.
func (*CancelResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_execute_proto_rawDescGZIP(), []int{4}
}

func (x *CancelResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *CancelResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_agent_v1_execute_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_execute_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_execute_proto_rawDescGZIP(), []int{5}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_agent_v1_execute_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_execute_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_execute_proto_rawDescGZIP(), []int{6}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

var File_agent_v1_execute_proto protoreflect.FileDescriptor

const file_agent_v1_execute_proto_rawDesc = "" +
	"\n" +
	"\x16agent/v1/execute.proto\x12\bagent.v1\"_\n" +
	"\x10UploadedDocument\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x1b\n" +
	"\tmime_type\x18\x02 \x01(\tR\bmimeType\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"\xe3\x01\n" +
	"\x0eExecuteRequest\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\x12\x15\n" +
	"\x06run_id\x18\x03 \x01(\tR\x05runId\x12\x19\n" +
	"\bagent_id\x18\x04 \x01(\tR\aagentId\x12!\n" +
	"\fuser_message\x18\x05 \x01(\tR\vuserMessage\x128\n" +
	"\tdocuments\x18\x06 \x03(\v2\x1a.agent.v1.UploadedDocumentR\tdocuments\"\xaa\x01\n" +
	"\fExecuteEvent\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x14\n" +
	"\x05delta\x18\x02 \x01(\tR\x05delta\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1b\n" +
	"\ttool_name\x18\x04 \x01(\tR\btoolName\x12\x1f\n" +
	"\vtool_detail\x18\x05 \x01(\tR\n" +
	"toolDetail\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\"&\n" +
	"\rCancelRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\":\n" +
	"\x0eCancelResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x0f\n" +
	"\rHealthRequest\"C\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId2\xcd\x01\n" +
	"\x12AgentWorkerService\x12=\n" +
	"\aExecute\x12\x18.agent.v1.ExecuteRequest\x1a\x16.agent.v1.ExecuteEvent0\x01\x12;\n" +
	"\x06Cancel\x12\x17.agent.v1.CancelRequest\x1a\x18.agent.v1.CancelResponse\x12;\n" +
	"\x06Health\x12\x17.agent.v1.HealthRequest\x1a\x18.agent.v1.HealthResponseB-Z+piper_agent/gateway/pkg/pb/agent/v1;agentv1b\x06proto3"

var (
	file_agent_v1_execute_proto_rawDescOnce sync.Once
	file_agent_v1_execute_proto_rawDescData []byte
)

func file_agent_v1_execute_proto_rawDescGZIP() []byte {
	file_agent_v1_execute_proto_rawDescOnce.Do(func() {
		file_agent_v1_execute_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_v1_execute_proto_rawDesc), len(file_agent_v1_execute_proto_rawDesc)))
	})
	return file_agent_v1_execute_proto_rawDescData
}

var file_agent_v1_execute_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_agent_v1_execute_proto_goTypes = []any{
	(*UploadedDocument)(nil), // 0: agent.v1.UploadedDocument
	(*ExecuteRequest)(nil),   // 1: agent.v1.ExecuteRequest
	(*ExecuteEvent)(nil),     // 2: agent.v1.ExecuteEvent
	(*CancelRequest)(nil),    // 3: agent.v1.CancelRequest
	(*CancelResponse)(nil),   // 4: agent.v1.CancelResponse
	(*HealthRequest)(nil),    // 5: agent.v1.HealthRequest
	(*HealthResponse)(nil),   // 6: agent.v1.HealthResponse
}
var file_agent_v1_execute_proto_depIdxs = []int32{
	0, // 0: agent.v1.ExecuteRequest.documents:type_name -> agent.v1.UploadedDocument
	1, // 1: agent.v1.AgentWorkerService.Execute:input_type -> agent.v1.ExecuteRequest
	3, // 2: agent.v1.AgentWorkerService.Cancel:input_type -> agent.v1.CancelRequest
	5, // 3: agent.v1.AgentWorkerService.Health:input_type -> agent.v1.HealthRequest
	2, // 4: agent.v1.AgentWorkerService.Execute:output_type -> agent.v1.ExecuteEvent
	4, // 5: agent.v1.AgentWorkerService.Cancel:output_type -> agent.v1.CancelResponse
	6, // 6: agent.v1.AgentWorkerService.Health:output_type -> agent.v1.HealthResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_agent_v1_execute_proto_init() }
func file_agent_v1_execute_proto_init() {
	if File_agent_v1_execute_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_v1_execute_proto_rawDesc), len(file_agent_v1_execute_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_v1_execute_proto_goTypes,
		DependencyIndexes: file_agent_v1_execute_proto_depIdxs,
		MessageInfos:      file_agent_v1_execute_proto_msgTypes,
	}.Build()
	File_agent_v1_execute_proto = out.File
	file_agent_v1_execute_proto_goTypes = nil
	file_agent_v1_execute_proto_depIdxs = nil
}
