// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.20.3
// source: runtime/v1/data.proto

package runtimev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RuntimeData_GetTokenData_FullMethodName = "/runtime.v1.RuntimeData/GetTokenData"
)

// RuntimeDataClient is the client API for RuntimeData service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RuntimeDataClient interface {
	GetTokenData(ctx context.Context, in *GetTokenDataRequest, opts ...grpc.CallOption) (*GetTokenDataResponse, error)
}

type runtimeDataClient struct {
	cc grpc.ClientConnInterface
}

func NewRuntimeDataClient(cc grpc.ClientConnInterface) RuntimeDataClient {
	return &runtimeDataClient{cc}
}

func (c *runtimeDataClient) GetTokenData(ctx context.Context, in *GetTokenDataRequest, opts ...grpc.CallOption) (*GetTokenDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTokenDataResponse)
	err := c.cc.Invoke(ctx, RuntimeData_GetTokenData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RuntimeDataServer is the server API for RuntimeData service.
// All implementations must embed UnimplementedRuntimeDataServer
// for forward compatibility.
type RuntimeDataServer interface {
	GetTokenData(context.Context, *GetTokenDataRequest) (*GetTokenDataResponse, error)
	mustEmbedUnimplementedRuntimeDataServer()
}

// UnimplementedRuntimeDataServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRuntimeDataServer struct{}

func (UnimplementedRuntimeDataServer) GetTokenData(context.Context, *GetTokenDataRequest) (*GetTokenDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTokenData not implemented")
}
func (UnimplementedRuntimeDataServer) mustEmbedUnimplementedRuntimeDataServer() {}
func (UnimplementedRuntimeDataServer) testEmbeddedByValue()                     {}

// UnsafeRuntimeDataServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RuntimeDataServer will
// result in compilation errors.
type UnsafeRuntimeDataServer interface {
	mustEmbedUnimplementedRuntimeDataServer()
}

func RegisterRuntimeDataServer(s grpc.ServiceRegistrar, srv RuntimeDataServer) {
	// If the following call panics, it indicates UnimplementedRuntimeDataServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RuntimeData_ServiceDesc, srv)
}

func _RuntimeData_GetTokenData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTokenDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeDataServer).GetTokenData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeData_GetTokenData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeDataServer).GetTokenData(ctx, req.(*GetTokenDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RuntimeData_ServiceDesc is the grpc.ServiceDesc for RuntimeData service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RuntimeData_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "runtime.v1.RuntimeData",
	HandlerType: (*RuntimeDataServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTokenData",
			Handler:    _RuntimeData_GetTokenData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "runtime/v1/data.proto",
}
