// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: runtime/v1/data.proto

package runtimev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTokenDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	TokenId       string                 `protobuf:"bytes,2,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTokenDataRequest) Reset() {
	*x = GetTokenDataRequest{}
	mi := &file_runtime_v1_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTokenDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokenDataRequest) ProtoMessage() {}

func (x *GetTokenDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokenDataRequest.ProtoReflect.Descriptor instead.
func (*GetTokenDataRequest) Descriptor() ([]byte, []int) {
	return file_runtime_v1_data_proto_rawDescGZIP(), []int{0}
}

func (x *GetTokenDataRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *GetTokenDataRequest) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

type GetTokenDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenId       string                 `protobuf:"bytes,1,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	PayloadJson   []byte                 `protobuf:"bytes,2,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTokenDataResponse) Reset() {
	*x = GetTokenDataResponse{}
	mi := &file_runtime_v1_data_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTokenDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokenDataResponse) ProtoMessage() {}

func (x *GetTokenDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_data_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokenDataResponse.ProtoReflect.Descriptor instead.
func (*GetTokenDataResponse) Descriptor() ([]byte, []int) {
	return file_runtime_v1_data_proto_rawDescGZIP(), []int{1}
}

func (x *GetTokenDataResponse) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

func (x *GetTokenDataResponse) GetPayloadJson() []byte {
	if x != nil {
		return x.PayloadJson
	}
	return nil
}

var File_runtime_v1_data_proto protoreflect.FileDescriptor

const file_runtime_v1_data_proto_rawDesc = "" +
	"\n" +
	"\x15runtime/v1/data.proto\x12\n" +
	"runtime.v1\"O\n" +
	"\x13GetTokenDataRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x19\n" +
	"\btoken_id\x18\x02 \x01(\tR\atokenId\"T\n" +
	"\x14GetTokenDataResponse\x12\x19\n" +
	"\btoken_id\x18\x01 \x01(\tR\atokenId\x12!\n" +
	"\fpayload_json\x18\x02 \x01(\fR\vpayloadJson2`\n" +
	"\vRuntimeData\x12Q\n" +
	"\fGetTokenData\x12\x1f.runtime.v1.GetTokenDataRequest\x1a .runtime.v1.GetTokenDataResponseB1Z/piper_agent/runtime/pkg/pb/runtime/v1;runtimev1b\x06proto3"

var (
	file_runtime_v1_data_proto_rawDescOnce sync.Once
	file_runtime_v1_data_proto_rawDescData []byte
)

func file_runtime_v1_data_proto_rawDescGZIP() []byte {
	file_runtime_v1_data_proto_rawDescOnce.Do(func() {
		file_runtime_v1_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_runtime_v1_data_proto_rawDesc), len(file_runtime_v1_data_proto_rawDesc)))
	})
	return file_runtime_v1_data_proto_rawDescData
}

var file_runtime_v1_data_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_runtime_v1_data_proto_goTypes = []any{
	(*GetTokenDataRequest)(nil),  // 0: runtime.v1.GetTokenDataRequest
	(*GetTokenDataResponse)(nil), // 1: runtime.v1.GetTokenDataResponse
}
var file_runtime_v1_data_proto_depIdxs = []int32{
	0, // 0: runtime.v1.RuntimeData.GetTokenData:input_type -> runtime.v1.GetTokenDataRequest
	1, // 1: runtime.v1.RuntimeData.GetTokenData:output_type -> runtime.v1.GetTokenDataResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_runtime_v1_data_proto_init() }
func file_runtime_v1_data_proto_init() {
	if File_runtime_v1_data_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_runtime_v1_data_proto_rawDesc), len(file_runtime_v1_data_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_runtime_v1_data_proto_goTypes,
		DependencyIndexes: file_runtime_v1_data_proto_depIdxs,
		MessageInfos:      file_runtime_v1_data_proto_msgTypes,
	}.Build()
	File_runtime_v1_data_proto = out.File
	file_runtime_v1_data_proto_goTypes = nil
	file_runtime_v1_data_proto_depIdxs = nil
}
