// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: runtime/v1/execute.proto

package runtimev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	v1 "piper_agent/runtime/pkg/pb/common/v1"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RunTemplateRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RequestId      string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	SessionId      string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,3,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	TemplateId     string                 `protobuf:"bytes,4,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	Vars           *v1.Vars               `protobuf:"bytes,5,opt,name=vars,proto3" json:"vars,omitempty"`
	ProxyId        string                 `protobuf:"bytes,6,opt,name=proxy_id,json=proxyId,proto3" json:"proxy_id,omitempty"`
	Engine         string                 `protobuf:"bytes,7,opt,name=engine,proto3" json:"engine,omitempty"` // "http" | "chrome"
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RunTemplateRequest) Reset() {
	*x = RunTemplateRequest{}
	mi := &file_runtime_v1_execute_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunTemplateRequest) ProtoMessage() {}

func (x *RunTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_execute_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunTemplateRequest.ProtoReflect.Descriptor instead.
func (*RunTemplateRequest) Descriptor() ([]byte, []int) {
	return file_runtime_v1_execute_proto_rawDescGZIP(), []int{0}
}

func (x *RunTemplateRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RunTemplateRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RunTemplateRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *RunTemplateRequest) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *RunTemplateRequest) GetVars() *v1.Vars {
	if x != nil {
		return x.Vars
	}
	return nil
}

func (x *RunTemplateRequest) GetProxyId() string {
	if x != nil {
		return x.ProxyId
	}
	return ""
}

func (x *RunTemplateRequest) GetEngine() string {
	if x != nil {
		return x.Engine
	}
	return ""
}

type RunTemplateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Status        *v1.RunStatus          `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunTemplateResponse) Reset() {
	*x = RunTemplateResponse{}
	mi := &file_runtime_v1_execute_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunTemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunTemplateResponse) ProtoMessage() {}

func (x *RunTemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_execute_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunTemplateResponse.ProtoReflect.Descriptor instead.
func (*RunTemplateResponse) Descriptor() ([]byte, []int) {
	return file_runtime_v1_execute_proto_rawDescGZIP(), []int{1}
}

func (x *RunTemplateResponse) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *RunTemplateResponse) GetStatus() *v1.RunStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type CancelRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	RunId         string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRunRequest) Reset() {
	*x = CancelRunRequest{}
	mi := &file_runtime_v1_execute_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRunRequest) ProtoMessage() {}

func (x *CancelRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_execute_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRunRequest.ProtoReflect.Descriptor instead.
func (*CancelRunRequest) Descriptor() ([]byte, []int) {
	return file_runtime_v1_execute_proto_rawDescGZIP(), []int{2}
}

func (x *CancelRunRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CancelRunRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type CancelRunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRunResponse) Reset() {
	*x = CancelRunResponse{}
	mi := &file_runtime_v1_execute_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRunResponse) ProtoMessage() {}

func (x *CancelRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_execute_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRunResponse.ProtoReflect.Descriptor instead.
func (*CancelRunResponse) Descriptor() ([]byte, []int) {
	return file_runtime_v1_execute_proto_rawDescGZIP(), []int{3}
}

type SubscribeRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	RunId         string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRunRequest) Reset() {
	*x = SubscribeRunRequest{}
	mi := &file_runtime_v1_execute_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRunRequest) ProtoMessage() {}

func (x *SubscribeRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_execute_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRunRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRunRequest) Descriptor() ([]byte, []int) {
	return file_runtime_v1_execute_proto_rawDescGZIP(), []int{4}
}

func (x *SubscribeRunRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SubscribeRunRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type RunEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *v1.RunStatus          `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunEvent) Reset() {
	*x = RunEvent{}
	mi := &file_runtime_v1_execute_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunEvent) ProtoMessage() {}

func (x *RunEvent) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_execute_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunEvent.ProtoReflect.Descriptor instead.
func (*RunEvent) Descriptor() ([]byte, []int) {
	return file_runtime_v1_execute_proto_rawDescGZIP(), []int{5}
}

func (x *RunEvent) GetStatus() *v1.RunStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *RunEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_runtime_v1_execute_proto protoreflect.FileDescriptor

const file_runtime_v1_execute_proto_rawDesc = "" +
	"\n" +
	"\x18runtime/v1/execute.proto\x12\n" +
	"runtime.v1\x1a\x15common/v1/types.proto\"\xf4\x01\n" +
	"\x12RunTemplateRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12'\n" +
	"\x0fidempotency_key\x18\x03 \x01(\tR\x0eidempotencyKey\x12\x1f\n" +
	"\vtemplate_id\x18\x04 \x01(\tR\n" +
	"templateId\x12#\n" +
	"\x04vars\x18\x05 \x01(\v2\x0f.common.v1.VarsR\x04vars\x12\x19\n" +
	"\bproxy_id\x18\x06 \x01(\tR\aproxyId\x12\x16\n" +
	"\x06engine\x18\a \x01(\tR\x06engine\"Z\n" +
	"\x13RunTemplateResponse\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12,\n" +
	"\x06status\x18\x02 \x01(\v2\x14.common.v1.RunStatusR\x06status\"H\n" +
	"\x10CancelRunRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\"\x13\n" +
	"\x11CancelRunResponse\"K\n" +
	"\x13SubscribeRunRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\"R\n" +
	"\bRunEvent\x12,\n" +
	"\x06status\x18\x01 \x01(\v2\x14.common.v1.RunStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xf3\x01\n" +
	"\x0eRuntimeExecute\x12N\n" +
	"\vRunTemplate\x12\x1e.runtime.v1.RunTemplateRequest\x1a\x1f.runtime.v1.RunTemplateResponse\x12H\n" +
	"\tCancelRun\x12\x1c.runtime.v1.CancelRunRequest\x1a\x1d.runtime.v1.CancelRunResponse\x12G\n" +
	"\fSubscribeRun\x12\x1f.runtime.v1.SubscribeRunRequest\x1a\x14.runtime.v1.RunEvent0\x01B1Z/piper_agent/runtime/pkg/pb/runtime/v1;runtimev1b\x06proto3"

var (
	file_runtime_v1_execute_proto_rawDescOnce sync.Once
	file_runtime_v1_execute_proto_rawDescData []byte
)

func file_runtime_v1_execute_proto_rawDescGZIP() []byte {
	file_runtime_v1_execute_proto_rawDescOnce.Do(func() {
		file_runtime_v1_execute_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_runtime_v1_execute_proto_rawDesc), len(file_runtime_v1_execute_proto_rawDesc)))
	})
	return file_runtime_v1_execute_proto_rawDescData
}

var file_runtime_v1_execute_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_runtime_v1_execute_proto_goTypes = []any{
	(*RunTemplateRequest)(nil),  // 0: runtime.v1.RunTemplateRequest
	(*RunTemplateResponse)(nil), // 1: runtime.v1.RunTemplateResponse
	(*CancelRunRequest)(nil),    // 2: runtime.v1.CancelRunRequest
	(*CancelRunResponse)(nil),   // 3: runtime.v1.CancelRunResponse
	(*SubscribeRunRequest)(nil), // 4: runtime.v1.SubscribeRunRequest
	(*RunEvent)(nil),            // 5: runtime.v1.RunEvent
	(*v1.Vars)(nil),             // 6: common.v1.Vars
	(*v1.RunStatus)(nil),        // 7: common.v1.RunStatus
}
var file_runtime_v1_execute_proto_depIdxs = []int32{
	6, // 0: runtime.v1.RunTemplateRequest.vars:type_name -> common.v1.Vars
	7, // 1: runtime.v1.RunTemplateResponse.status:type_name -> common.v1.RunStatus
	7, // 2: runtime.v1.RunEvent.status:type_name -> common.v1.RunStatus
	0, // 3: runtime.v1.RuntimeExecute.RunTemplate:input_type -> runtime.v1.RunTemplateRequest
	2, // 4: runtime.v1.RuntimeExecute.CancelRun:input_type -> runtime.v1.CancelRunRequest
	4, // 5: runtime.v1.RuntimeExecute.SubscribeRun:input_type -> runtime.v1.SubscribeRunRequest
	1, // 6: runtime.v1.RuntimeExecute.RunTemplate:output_type -> runtime.v1.RunTemplateResponse
	3, // 7: runtime.v1.RuntimeExecute.CancelRun:output_type -> runtime.v1.CancelRunResponse
	5, // 8: runtime.v1.RuntimeExecute.SubscribeRun:output_type -> runtime.v1.RunEvent
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_runtime_v1_execute_proto_init() }
func file_runtime_v1_execute_proto_init() {
	if File_runtime_v1_execute_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_runtime_v1_execute_proto_rawDesc), len(file_runtime_v1_execute_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_runtime_v1_execute_proto_goTypes,
		DependencyIndexes: file_runtime_v1_execute_proto_depIdxs,
		MessageInfos:      file_runtime_v1_execute_proto_msgTypes,
	}.Build()
	File_runtime_v1_execute_proto = out.File
	file_runtime_v1_execute_proto_goTypes = nil
	file_runtime_v1_execute_proto_depIdxs = nil
}
