// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.20.3
// source: runtime/v1/template.proto

package runtimev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RuntimeTemplate_ValidateTemplate_FullMethodName = "/runtime.v1.RuntimeTemplate/ValidateTemplate"
	RuntimeTemplate_UpsertTemplate_FullMethodName   = "/runtime.v1.RuntimeTemplate/UpsertTemplate"
)

// RuntimeTemplateClient is the client API for RuntimeTemplate service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RuntimeTemplateClient interface {
	ValidateTemplate(ctx context.Context, in *ValidateTemplateRequest, opts ...grpc.CallOption) (*ValidateTemplateResponse, error)
	UpsertTemplate(ctx context.Context, in *UpsertTemplateRequest, opts ...grpc.CallOption) (*UpsertTemplateResponse, error)
}

type runtimeTemplateClient struct {
	cc grpc.ClientConnInterface
}

func NewRuntimeTemplateClient(cc grpc.ClientConnInterface) RuntimeTemplateClient {
	return &runtimeTemplateClient{cc}
}

func (c *runtimeTemplateClient) ValidateTemplate(ctx context.Context, in *ValidateTemplateRequest, opts ...grpc.CallOption) (*ValidateTemplateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateTemplateResponse)
	err := c.cc.Invoke(ctx, RuntimeTemplate_ValidateTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeTemplateClient) UpsertTemplate(ctx context.Context, in *UpsertTemplateRequest, opts ...grpc.CallOption) (*UpsertTemplateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertTemplateResponse)
	err := c.cc.Invoke(ctx, RuntimeTemplate_UpsertTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RuntimeTemplateServer is the server API for RuntimeTemplate service.
// All implementations must embed UnimplementedRuntimeTemplateServer
// for forward compatibility.
type RuntimeTemplateServer interface {
	ValidateTemplate(context.Context, *ValidateTemplateRequest) (*ValidateTemplateResponse, error)
	UpsertTemplate(context.Context, *UpsertTemplateRequest) (*UpsertTemplateResponse, error)
	mustEmbedUnimplementedRuntimeTemplateServer()
}

// UnimplementedRuntimeTemplateServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRuntimeTemplateServer struct{}

func (UnimplementedRuntimeTemplateServer) ValidateTemplate(context.Context, *ValidateTemplateRequest) (*ValidateTemplateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateTemplate not implemented")
}
func (UnimplementedRuntimeTemplateServer) UpsertTemplate(context.Context, *UpsertTemplateRequest) (*UpsertTemplateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpsertTemplate not implemented")
}
func (UnimplementedRuntimeTemplateServer) mustEmbedUnimplementedRuntimeTemplateServer() {}
func (UnimplementedRuntimeTemplateServer) testEmbeddedByValue()                         {}

// UnsafeRuntimeTemplateServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RuntimeTemplateServer will
// result in compilation errors.
type UnsafeRuntimeTemplateServer interface {
	mustEmbedUnimplementedRuntimeTemplateServer()
}

func RegisterRuntimeTemplateServer(s grpc.ServiceRegistrar, srv RuntimeTemplateServer) {
	// If the following call panics, it indicates UnimplementedRuntimeTemplateServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RuntimeTemplate_ServiceDesc, srv)
}

func _RuntimeTemplate_ValidateTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeTemplateServer).ValidateTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeTemplate_ValidateTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeTemplateServer).ValidateTemplate(ctx, req.(*ValidateTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeTemplate_UpsertTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeTemplateServer).UpsertTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeTemplate_UpsertTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeTemplateServer).UpsertTemplate(ctx, req.(*UpsertTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RuntimeTemplate_ServiceDesc is the grpc.ServiceDesc for RuntimeTemplate service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RuntimeTemplate_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "runtime.v1.RuntimeTemplate",
	HandlerType: (*RuntimeTemplateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ValidateTemplate",
			Handler:    _RuntimeTemplate_ValidateTemplate_Handler,
		},
		{
			MethodName: "UpsertTemplate",
			Handler:    _RuntimeTemplate_UpsertTemplate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "runtime/v1/template.proto",
}
