# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from web_crawler_agent.pb.agent.v1 import execute_pb2 as agent_dot_v1_dot_execute__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in agent/v1/execute_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentWorkerServiceStub:
    """Web 网关调用的 Python 子 Agent Worker（与 runtime.v1 采集 RPC 分离）。
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Execute = channel.unary_stream(
                '/agent.v1.AgentWorkerService/Execute',
                request_serializer=agent_dot_v1_dot_execute__pb2.ExecuteRequest.SerializeToString,
                response_deserializer=agent_dot_v1_dot_execute__pb2.ExecuteEvent.FromString,
                _registered_method=True)
        self.Cancel = channel.unary_unary(
                '/agent.v1.AgentWorkerService/Cancel',
                request_serializer=agent_dot_v1_dot_execute__pb2.CancelRequest.SerializeToString,
                response_deserializer=agent_dot_v1_dot_execute__pb2.CancelResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/agent.v1.AgentWorkerService/Health',
                request_serializer=agent_dot_v1_dot_execute__pb2.HealthRequest.SerializeToString,
                response_deserializer=agent_dot_v1_dot_execute__pb2.HealthResponse.FromString,
                _registered_method=True)


class AgentWorkerServiceServicer:
    """Web 网关调用的 Python 子 Agent Worker（与 runtime.v1 采集 RPC 分离）。
    """

    def Execute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Cancel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentWorkerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Execute': grpc.unary_stream_rpc_method_handler(
                    servicer.Execute,
                    request_deserializer=agent_dot_v1_dot_execute__pb2.ExecuteRequest.FromString,
                    response_serializer=agent_dot_v1_dot_execute__pb2.ExecuteEvent.SerializeToString,
            ),
            'Cancel': grpc.unary_unary_rpc_method_handler(
                    servicer.Cancel,
                    request_deserializer=agent_dot_v1_dot_execute__pb2.CancelRequest.FromString,
                    response_serializer=agent_dot_v1_dot_execute__pb2.CancelResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=agent_dot_v1_dot_execute__pb2.HealthRequest.FromString,
                    response_serializer=agent_dot_v1_dot_execute__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agent.v1.AgentWorkerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agent.v1.AgentWorkerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentWorkerService:
    """Web 网关调用的 Python 子 Agent Worker（与 runtime.v1 采集 RPC 分离）。
    """

    @staticmethod
    def Execute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/agent.v1.AgentWorkerService/Execute',
            agent_dot_v1_dot_execute__pb2.ExecuteRequest.SerializeToString,
            agent_dot_v1_dot_execute__pb2.ExecuteEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Cancel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.v1.AgentWorkerService/Cancel',
            agent_dot_v1_dot_execute__pb2.CancelRequest.SerializeToString,
            agent_dot_v1_dot_execute__pb2.CancelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.v1.AgentWorkerService/Health',
            agent_dot_v1_dot_execute__pb2.HealthRequest.SerializeToString,
            agent_dot_v1_dot_execute__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
